config/routes.rb
Rails.application.routes.draw do
  root "flights#index"
  get 'flights/index' => 'flights#index', as: :flights
  get 'bookings/index'
  get 'bookings/new' => 'bookings#new', as: :new_booking
  resources :bookings
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: 'Flight', foreign_key: 'departure_airport_id'
  has_many :arriving_flights, class_name: 'Flight', foreign_key: 'arrival_airport_id'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers
  accepts_nested_attributes_for :passengers

  attr_accessor :passenger_count
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: 'Airport', foreign_key: 'departure_airport_id'
  belongs_to :arrival_airport, class_name: 'Airport', foreign_key: 'arrival_airport_id'
  has_many :bookings

  attr_accessor :flight_code

  scope :by_departure_airport, ->(code) { where(departure_airport: Airport.find_by(code: code)) if code.present? }
  scope :by_arrival_airport, ->(code) { where(arrival_airport: Airport.find_by(code: code)) if code.present? }
  scope :by_passenger, ->(passenger) { where("available_seats >= ?", passenger) if passenger.present? }
  scope :by_date, ->(date) { where(start_datetime: date.to_date.beginning_of_day..date.to_date.end_of_day) if date.present? }
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
    @flight = Flight.find(@booking.flight_id)
    @flight.flight_code = 'Code' + @flight.id.to_s
  end

  def new
    @flight = Flight.find(params[:flight_id])
    @booking = Booking.new(flight_id: @flight.id, passenger_count: params[:passenger_count])
    @booking.passenger_count.to_i.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      PassengerMailer.booking_confirmation(@booking).deliver_later
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, :passenger_count, passengers_attributes: [:name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.all
    @flights = @flights.by_departure_airport(params[:departure_code])
    @flights = @flights.by_arrival_airport(params[:arrival_code])
    @flights = @flights.by_passenger(params[:passenger])
    @flights = @flights.by_date(params[:flight_date])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<%= form_for @booking do |f| %>
  <%= f.hidden_field :flight_id %>
  <%= f.hidden_field :passenger_count %>
  <%= f.label :flight_date %>
  <%= @flight.start_datetime %>
  <%= f.label :departure_airport %>
  <%= @flight.departure_airport.code %>
  <%= f.label :arrival_airport %>
  <%= @flight.arrival_airport.code %>
  <%= f.fields_for :passengers do |passenger_form| %>
    <%= passenger_form.label :name %>
    <%= passenger_form.text_field :name %>
    <%= passenger_form.label :email %>
    <%= passenger_form.text_field :email %>
  <% end %>
  <%= f.submit "Book Flight" %>
<% end %>

app/views/bookings/show.html.erb
<p> Flight Information: 
<%= @booking.flight.flight_code %> 
<%= @booking.flight.departure_airport.code %> -> <%= @booking.flight.arrival_airport.code %> 
<%= @booking.flight.start_datetime %> </p>
<h2>Passenger Information:</h2>
<% @booking.passengers.each do |passenger| %>
  <p> Name: <%= passenger.name %> </p>
  <p> Email: <%= passenger.email %> </p>
<% end %>

app/views/flights/index.html.erb
<h1>Flights</h1>

<%= form_tag new_booking_path, method: :get do %>
  <table>
    <thead>
      <tr>
        <th>Departure</th>
        <th>Arrival</th>
        <th>Start Time</th>
        <th>Duration</th>
        <th>Select</th>
      </tr>
    </thead>
    <tbody>
      <% if @flights.any? %>
        <% @flights.each do |flight| %>
          <tr>
            <td><%= flight.departure_airport.code %></td>
            <td><%= flight.arrival_airport.code %></td>
            <td><%= flight.start_datetime %></td>
            <td><%= flight.duration %></td>
            <td><%= radio_button_tag 'flight_id', flight.id %></td>
            <td><%= label_tag :passenger, "Number of Passengers" %>
                <%= select_tag :passenger_count, options_for_select(1..4) %>
            </td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="5">No flights found</td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= submit_tag "Select Flight" %>
<% end %>


<%= form_tag flights_path, method: :get do %>
  <%= label_tag :departure_code, "Departure Airport" %>
  <%= select_tag :departure_code, options_from_collection_for_select(Airport.all, :code, :code) %>
  <br>

  <%= label_tag :arrival_code, "Arrival Airport" %>
  <%= select_tag :arrival_code, options_from_collection_for_select(Airport.all, :code, :code) %>
  <br>

  <%= label_tag :flight_date, "Flight Date" %>
  <%= select_tag :flight_date, options_for_select(Flight.all.map{|f| f.start_datetime.to_date}.uniq) %>
  <br>

  <%= submit_tag "Search" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>